.github/workflows/release.yml
Removes deprecated flag https://goreleaser.com/deprecations/#-rm-dist
=> fix: remove deprecated --rm-dist flag

cmd/generate-raid.go
this fixes an issue where newlines in test requirements description was making go staticcheck package to throw several different warnings throughout generated armory.go file
=> fix: remove newlines from test_requirements description to fix go staticcheck warnings 

cmd/generate-raid.go
this fixes an issue where some words were concatenated and the strings were left with trailing whitesapce
=> fix: replace newline with space and trim spaces

cmd/generate-raid.go
relates to https://github.com/privateerproj/raid-generator-templates/pull/1/files
=> Updated to match new CCC structs

.github/workflows/pr-title.yml
we're going to start implementing [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) for PR titles to help maintainers get a quick view into what the PR is for
=> feat: add pr title validation

cmd/root.go
currently privateer installs to `~/.privateer/bin` but the default directory for raids is `~/privateer/bin`.
=> fix: Changed defaultBinariesPath to match install.sh path

.gitignore
So no one accidentally source controls them
=> fix: add generated generated-raids folders to .gitignore

cmd/list.go
When the privateer binary list command is executed, do not show the privateer binary.
=> chore: Don't list privateer binary when listing plugins

.github/security-insights.yml
this SI file contains only repo information, and pulls project info from https://github.com/privateerproj/privateer/blob/main/.github/security-insights.yml
cc/ @grudra7714 and @jmeridth I've included you both in the `Core Team` list for this repo
=> chore: added security insights file

.github/security-insights.yml
Turns out the parent-si-source needs to be a url that returns the YAML instead of a github HTML page... go figure.
=> chore: Update parent SI source path

.github/workflows/goreleaser.yml, .goreleaser.yaml
Fixes #12
- copy over pieces we need from old config
- verified good with `goreleaser check`
Our new release github action will create the release and do all the templating based on conventional commits pr titles and auto-labelling.  Now goreleaser will see the newly published release and attach the new asset builds to the new release.
Was tested in https://github.com/jmeridth/test-reusable-release-with-goreleaser
=> fix: goreleaser stuff

Dockerfile
To test locally:
build the image:
```bash
docker build . --tag privateer:0.2.0
```
run a temporary image, passing in the config file from local:
```bash
docker run -it --rm --name debug -v ./config.yml:/app/config.yml privateer:0.2.0
```
currently only displays help command
image is currently 32.7MB
=> chore: add Dockerfile to build release image

docs/how-to-generate-example-plugin.md
=> docs: update how-to-generate-example-plugin.md with missing parts

cmd/root.go, go.mod, go.sum
Related to https://github.com/privateerproj/privateer-sdk/pull/54
=> chore: update after removal of readconfig func

.github/release-drafter.yml
> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backward compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.
https://semver.org/#spec-item-6
=> ci: Bugs should increment patch version

.github/workflows/ci.yml, .github/workflows/site.yml, docs/how-to-generate-example-plugin.md
New release includes the non-duplicated entry.  Huzzah!
=> docs: update how-to-generate-example-plugin.md

.github/workflows/auto-labeler.yml, .goreleaser.yaml
- https://github.com/privateerproj/privateer/actions/runs/12999165564/job/36253914307#step:4:23-23
=> chore: auto-labeler workflow perms and goreleaser config

cmd/generate-plugin.go, go.mod, go.sum
I'm not sure why this still isn't getting SCI by version number, but it seems to be working to pull main, which is all we need for now.
=> chore: updated to use latest SCI in the generator

.github/workflows/ci.yml, build/github/acceptance_test.sh, test/data/CCC.VPC_2025.01.yaml
Added the Acceptance job to the ci.yml
Added build/github directory for storing scripts
Added test/data directory for files needed for tests as per a nice little project I found for project structure standards:
https://github.com/golang-standards/project-layout
This acceptance test runs all the top level privateer commands and passes/fails based on the return of the command run.
[resolves]https://github.com/revanite-io/roadmap/issues/24#event-16789338772
=> test: Add acceptance tests to CI workflow

.github/CODEOWNERS, .github/dependabot.yml
Update dependabot to not add labels to its PRs. It is colliding with our auto labeller and releases when `major`, `minor`, or `patch` labels are auto added to Dependabot PRs by Dependabot
=> fix: update Dependabot labels

.github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/release.yml
Goreleaser will fail if we do not use the version we use in `go.mod` this solution is the best in case we upgrade the version in `go.mod` again and forget to update the workflow or Dependabot misses it to.
[Docs](https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file)
=> chore: get go version file for workflows from go.mod
